// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxQeo2zJYdtR2yLArGcg84r17nPnjtKzc',
    appId: '1:634242710011:web:e0b046cc2c9b31be92b35e',
    messagingSenderId: '634242710011',
    projectId: 'projetoflutter-c0519',
    authDomain: 'projetoflutter-c0519.firebaseapp.com',
    storageBucket: 'projetoflutter-c0519.firebasestorage.app',
    measurementId: 'G-B60DZX6YXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwAQgAiRR54xdCaiU38nv0jDlmZ1WRKpU',
    appId: '1:634242710011:android:b2e654b5b335d55792b35e',
    messagingSenderId: '634242710011',
    projectId: 'projetoflutter-c0519',
    storageBucket: 'projetoflutter-c0519.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGGlFmH5VECWg399vmIYVvH_1UiJIOsWQ',
    appId: '1:634242710011:ios:c2a2f462616b820892b35e',
    messagingSenderId: '634242710011',
    projectId: 'projetoflutter-c0519',
    storageBucket: 'projetoflutter-c0519.firebasestorage.app',
    iosBundleId: 'com.example.appAluno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGGlFmH5VECWg399vmIYVvH_1UiJIOsWQ',
    appId: '1:634242710011:ios:c2a2f462616b820892b35e',
    messagingSenderId: '634242710011',
    projectId: 'projetoflutter-c0519',
    storageBucket: 'projetoflutter-c0519.firebasestorage.app',
    iosBundleId: 'com.example.appAluno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxQeo2zJYdtR2yLArGcg84r17nPnjtKzc',
    appId: '1:634242710011:web:f854431c33f7b01092b35e',
    messagingSenderId: '634242710011',
    projectId: 'projetoflutter-c0519',
    authDomain: 'projetoflutter-c0519.firebaseapp.com',
    storageBucket: 'projetoflutter-c0519.firebasestorage.app',
    measurementId: 'G-XGXN07S4YJ',
  );
}
